alias a='sudo apt update && sudo apt full-upgrade -y && sudo apt-get dist-upgrade && sudo apt autoremove -y && sudo apt clean && clear && echo "Todo Actualizado..."'
alias ab='sudo source /home/walli/.bash_aliases && sudo source /home/walli/.bashrc'
alias aliass='sudo nano /home/walli/.bash_aliases'
alias baulera='cd /home/walli/.baulera'
alias h='hollywood'
alias l='exa -CF'
alias la='exa -la'
alias ll='exa -lh'
alias ls='exa'
alias m='cmatrix'
alias man='man -L es'
alias n='neofetchalias'
alias rc='sudo nano /home/walli/.bashrc'
#alias temp='vcgencmd measure_temp | cut -d= -f2'
#alias volts='vcgencmd measure_volts | cut -d= -f2'
alias descargas='cd /home/walli/Desacargas'
alias musica='cd /home/walli/Musica'
alias imagenes='cd /home/walli/Imagenes'