alias aliass='nano $HOME/.bash_aliases'
alias ab='source $HOME/.bashrc'
alias a='sudo apt update && sudo apt full-upgrade -y && sudo apt-get dist-upgrade && sudo apt autoremove -y && sudo apt clean && clear && echo "Todo Actualizado..."'
alias m='cmatrix'
alias h='hollywood'
alias baulera='cd /home/$USER/.baulera'
alias ll='exa -lh'
alias la='exa -la'
alias l='exa -CF'
alias temp='vcgencmd measure_temp | cut -d= -f2'
alias volts='vcgencmd measure_volts | cut -d= -f2'
alias man='man -L es'
alias rc='nano $HOME/.bashrc'
alias ls='exa'