#!/bin/bash

# Configurando mi terminal
mkdir -p "/home/walli/.baulera"
mkdir -p "/home/walli/Descargas"
mkdir -p "/home/walli/Imagenes"
mkdir -p "/home/walli/Musica"


cp -R .docker_config "/home/walli/.docker_config"
cp -R .bash_aliases "/home/walli/"
cp -R .bashrc "/home/walli/"
cp -R mis-scripts "/home/walli/.baulera/mis-scripts"
chmod -R +x "/home/walli/.baulera/mis-scripts"

source "/home/walli/.bash_aliases"
source "/home/walli/.bashrc"
