#!/bin/bash

# Verificar privilegios de superusuario
if [ "$(id -u)" -ne 0 ]; then
    echo "Este script necesita ser ejecutado con privilegios de superusuario."
    exit 1
fi

# Lista de herramientas a instalar
tools=(
    "neofetch"
    "btop"
    "wget"
    "curl"
    "cmatrix"
    "hollywood"
    "man"
    "manpages-es"
    "zip"
    "exa"
)

# Función para mostrar barra de progreso
show_progress() {
    local elapsed=$1
    local total=$2
    local progress=$((elapsed * 100 / total))
    printf "[%-100s] %d%%\r" "$bar" "$progress"
}

# Instalar herramientas
for tool in "${tools[@]}"; do
    echo "Instalando $tool..."
    bar="...................................................................................................."
    length=${#bar}
    count=0
    apt install "$tool" -y > /dev/null 2>&1 &
    pid=$!
    while kill -0 $pid 2>/dev/null; do
        show_progress $count $length
        sleep 0.1
        count=$((count+1))
    done
    wait $pid
    show_progress $length $length
    echo ""
    if [ $? -eq 0 ]; then
        echo "$tool se ha instalado correctamente."
    else
        echo "Error al instalar $tool. ¡Abortando!"
        exit 1
    fi
done

echo "Instalación completa."
