#!/bin/bash

# Verificar privilegios de superusuario
if [ "$(id -u)" -ne 0 ]; then
    echo "Este script necesita ser ejecutado con privilegios de superusuario."
    exit 1
fi

# Lista de herramientas a instalar
tools=(
    "neofetch"
    "btop"
    "wget"
    "curl"
    "cmatrix"
    "hollywood"
    "man"
    "manpages-es"
    "zip"
    "exa"
    "python3" 
    "python3-pip"
)

# Inicializar listas de herramientas instaladas y no instaladas
installed_tools=()
failed_tools=()

# Instalar herramientas
for tool in "${tools[@]}"; do
    echo "Instalando $tool..."
    sudo apt install "$tool" -y > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "$tool se ha instalado correctamente."
        installed_tools+=("$tool")
    else
        echo "Error al instalar $tool. ¡Abortando!"
        failed_tools+=("$tool")
    fi
done

echo
echo "Herramientas instaladas correctamente:"
printf '%s\n' "${installed_tools[@]}"
echo

if [ ${#failed_tools[@]} -gt 0 ]; then
    echo
    echo "Herramientas que no se pudieron instalar:"
    printf '%s\n' "${failed_tools[@]}"
    echo
fi

