#!/bin/bash

opcion=""

while [ "$opcion" != "q" ]; do
  echo
  echo "    Menú de opciones:"
  echo
  echo "1) Configurar mi terminal"
  echo "2) Instalar Herramientas"
  echo "3) Instalar OpenMediaVault"
  echo "4) Actualizar Servidor"
  echo "5) Configurar git"
  echo "q) Salir"
  echo
  read -p "Elije una opcion: " opcion
  echo

  case $opcion in
    1)
      # Configurando mi terminal
      
      #Creando carpeta .baulera
      mkdir -p $HOME/.baulera

      #Copiando archivo .bash_aliases donde corresponde.
      cp -R .bash_aliases $HOME
      source $HOME/.bash_aliases

      #Copiando archivo .bashrc donde corresponde
      cp -R  .bashrc $HOME

      #Copiando carpeta mis-scripts donde corresponde

      cp -R mis-scripts $HOME/.baulera/mis-scripts
      chmod -R +x $HOME/.baulera/mis-scripts
      
      #Actualizar .bashrc
      source $HOME/.bashrc

      ;;
    2)
      #Instalar Herramientas

      sudo apt install neofetch -y
      sudo apt install wget -y
      sudo apt install curl -y
      sudo apt install cmatrix -y
      sudo apt install hollywood -y
      sudo apt install man -y
      sudo apt install manpages-es
      dpkg-reconfigure locales
      sudo apt install zip -y
      sudo apt install exa -y
      sudo apt install python3 -y
      echo "Herramientas Instaladas"

      echo
      ;;
    3)
      # Instrucciones para la opción 3
      #Instalando OpenMediaVault
      wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
      echo "...Open Media Vault Instalado..."
      echo
      ;;
    4)
      # Instrucciones para la opción 4
      alias a='sudo apt update && sudo apt full-upgrade -y && sudo apt-get dist-upgrade && sudo apt autoremove -y && sudo apt clean && clear && echo "Todo Actualizado..."'
      echo "...Todo actualizado..."
      echo
      ;;
    5)
      #Instalando GIT.
      sudo apt install git -y

      #Configurando usuario de GitHub.

      echo 'Email en GitHub: '
      read email
      echo 'Usuario en GitHub: '
      read usuario

      git config --global user.email "$email"
      git config --global user.name "$usuario"

      echo "Git configurado correctamente"
      echo
      ;;
    q)
      # Instrucciones para salir
      echo "Saliendo del menú..."
      ;;
    *)
      # Instrucciones para una entrada inválida
      echo "Opción inválida. Inténtelo de nuevo."
      echo
      ;;
  esac
done