version: '3'

services:
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:linux-arm64-2.19.4
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - "/home/walli/.docker_config/portainer/docker.sock:/var/run/docker.sock"
            - "/home/walli/.docker_config/portainer/portainer_data:/data"
        environment:
            - TZ=America/Argentina/Buenos_Aires

volumes:
    portainer_data: